# Generated by Django 2.2.1 on 2019-05-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESA2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lehrveranstaltung',
            old_name='name',
            new_name='bezeichnung',
        ),
    ]
