# Generated by Django 2.2.1 on 2019-05-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESA2', '0002_auto_20190522_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='lehrveranstaltung',
            name='teilnehmer',
            field=models.ManyToManyField(to='ESA2.Student'),
        ),
    ]
