# Generated by Django 2.2.1 on 2019-05-22 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ESA2', '0003_lehrveranstaltung_teilnehmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einschreibung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='lehrveranstaltung',
            name='teilnehmer',
            field=models.ManyToManyField(through='ESA2.Einschreibung', to='ESA2.Student'),
        ),
        migrations.AddField(
            model_name='einschreibung',
            name='lehrveranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ESA2.Lehrveranstaltung'),
        ),
        migrations.AddField(
            model_name='einschreibung',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ESA2.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='lehrveranstaltungen',
            field=models.ManyToManyField(through='ESA2.Einschreibung', to='ESA2.Lehrveranstaltung'),
        ),
    ]
