# Generated by Django 2.2.1 on 2019-05-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESA2', '0004_auto_20190522_2350'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='einschreibung',
            table='einschreibung',
        ),
    ]
